baseURL = 'https://abenezerkb.github.io'
languageCode = 'en-us'
title = 'Abenezer'
theme = "hugo-blog-awesome"

# Main menu
[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 3

[[params.socialIcons]]
name = "github"
url = "https://github.com/AbenezerKb"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/dev-abenezer"
[params]
  goToTop = true
